version: '3.9'

services:

  nginx:
    build:
      context: ../..
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8002:80
    networks:
      - backend


  php-fpm:
    build:
      context: ../..
      dockerfile: php-fpm/Dockerfile
    restart: unless-stopped
    container_name: php
    volumes:
      - ../:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      - backend
  es:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      ports:
          - "9200:9200"
          - "9300:9300"
      environment:
          - discovery.type=single-node
      networks:
        - backend


  redis:
      image: redis:alpine
      container_name: myapp-redis
      command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
      volumes:
          - ./data/redis:/data
      ports:
          - "6379:6379"
      networks:
          - backend
  mysql:
      image: bitnami/mariadb:latest
      restart: always
      environment:
          MARIADB_ROOT_PASSWORD: root123
          MYSQL_DATABASE: laravel2

      ports:
          - 3306:3306

      networks:
       - backend



networks:
  backend:
    name: My_network
    driver: bridge


